[valuestore]
Master = true
NetFilter = ["10.0.0.0/8"]
Port = 8443
MsgRingPort = 8001
CmdCtrlPort = 4444
StorePort = 6379
CertFile = "/etc/syndicate/server.crt"
KeyFile = "/etc/syndicate/server.key"
RingDir = "/etc/syndicate/ring"
WeightAssignment = "self"

[groupstore]
Master = true
NetFilter = ["10.0.0.0/8"]
Port = 8444
MsgRingPort = 8002
CmdCtrlPort = 4445
StorePort = 6380
CertFile = "/etc/syndicate/server.crt"
KeyFile = "/etc/syndicate/server.key"
RingDir = "/etc/syndicate/ring"
WeightAssignment = "self"

#[llamasherpaderpa2000]
#Master = true
#Slaves = []
#NetFilter = ["192.168.1.1/27"]
#Port = 8445
#CmdCtrlPort = 4445
